<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-11-08T23:37:27 IST" name="Default suite" finished-at="2023-11-08T23:37:41 IST" duration-ms="14430">
    <groups>
    </groups>
    <test started-at="2023-11-08T23:37:27 IST" name="Default test" finished-at="2023-11-08T23:37:41 IST" duration-ms="14430">
      <class name="testScripts.CreatecategoryTest">
        <test-method is-config="true" signature="classConfig()[pri:0, instance:testScripts.CreatecategoryTest@18078bef]" started-at="2023-11-08T23:37:27 IST" name="classConfig" finished-at="2023-11-08T23:37:29 IST" duration-ms="2087" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classConfig -->
        <test-method is-config="true" signature="methodConfi()[pri:0, instance:testScripts.CreatecategoryTest@18078bef]" started-at="2023-11-08T23:37:29 IST" name="methodConfi" finished-at="2023-11-08T23:37:35 IST" duration-ms="6115" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodConfi -->
        <test-method signature="createCategoryTest()[pri:0, instance:testScripts.CreatecategoryTest@18078bef]" started-at="2023-11-08T23:37:35 IST" name="createCategoryTest" finished-at="2023-11-08T23:37:40 IST" duration-ms="5155" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Add New category] but found [Add New Category],
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Add New category] but found [Add New Category],
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testScripts.CreatecategoryTest.createCategoryTest(CreatecategoryTest.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createCategoryTest -->
        <test-method is-config="true" signature="methodTeardown()[pri:0, instance:testScripts.CreatecategoryTest@18078bef]" started-at="2023-11-08T23:37:40 IST" name="methodTeardown" finished-at="2023-11-08T23:37:41 IST" duration-ms="805" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodTeardown -->
        <test-method is-config="true" signature="classTeardown()[pri:0, instance:testScripts.CreatecategoryTest@18078bef]" started-at="2023-11-08T23:37:41 IST" name="classTeardown" finished-at="2023-11-08T23:37:41 IST" duration-ms="214" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classTeardown -->
      </class> <!-- testScripts.CreatecategoryTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
